services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - "./localstack:/var/lib/localstack"
      
  postgres:
    image: 'postgres:15'
    container_name: db
    environment:
      - 'POSTGRES_DB=ipredencao_manager'
      - 'POSTGRES_PASSWORD=ipredencao_manager'
      - 'POSTGRES_USER=ipredencao_manager'
    ports:
      - '54329:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "ipredencao_manager" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s

volumes:
  pgdata:
