spring.application.name=ipredencao-manager

# DB
spring.datasource.url=jdbc:postgresql://localhost:54329/ipredencao_manager
spring.datasource.username=ipredencao_manager
spring.datasource.password=ipredencao_manager
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase
spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# JOOQ
spring.jooq.sql-dialect=POSTGRES
