ALTER TABLE formulario_pessoa
ADD COLUMN IF NOT EXISTS bairro VARCHAR(255);

ALTER TABLE pessoa 
ADD COLUMN IF NOT EXISTS bookmark BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE pessoa_history 
ADD COLUMN IF NOT EXISTS bookmark BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_pessoa_bookmark ON pessoa(bookmark);
