#!/bin/bash
set -e

# Script para criar tabelas no RDS manualmente
# Uso: ./create-tables-rds.sh

echo "📊 Criando tabelas no RDS..."
echo ""

# Configurações
RDS_ENDPOINT="ipredencao-manager-prod-db.cqon6ha0kufq.us-east-1.rds.amazonaws.com"
DB_NAME="ipredencao_manager"
DB_USER="ipredencao_admin"
DB_PASSWORD="${DB_PASSWORD:-ipredencao_manager}"

# Combinar os arquivos SQL
echo "📦 Preparando scripts SQL..."
cat src/main/resources/db/changelog/V001__2025-07-08_tables.sql \
    src/main/resources/db/changelog/V002__2025-08-19_auth_tables.sql \
    > /tmp/create-all-tables.sql

echo "✅ Scripts SQL preparados"
echo ""

# Instruções para executar
echo "=========================================="
echo "⚠️  NOTA IMPORTANTE"
echo "=========================================="
echo ""
echo "O RDS não é publicamente acessível."
echo "Você precisa:"
echo ""
echo "1. Criar um bastion host (EC2) na mesma VPC"
echo "   OU"
echo "2. Temporariamente permitir sua conexão local"
echo ""
echo "=========================================="
echo "Opção 1: Via EC2 Bastion (Recomendado)"
echo "=========================================="
echo ""
echo "# 1. Lance uma EC2 na mesma VPC/Subnet do RDS"
echo "# 2. SSH para a EC2"
echo "# 3. Instale PostgreSQL client:"
echo "   sudo yum install -y postgresql15"
echo ""
echo "# 4. Copie o SQL:"
echo "   scp /tmp/create-all-tables.sql ec2-user@<ec2-ip>:/tmp/"
echo ""
echo "# 5. Execute no RDS:"
echo "   PGPASSWORD='$DB_PASSWORD' psql \\"
echo "     -h $RDS_ENDPOINT \\"
echo "     -U $DB_USER \\"
echo "     -d $DB_NAME \\"
echo "     -f /tmp/create-all-tables.sql"
echo ""
echo "=========================================="
echo "Opção 2: Via RDS Query Editor (Console)"
echo "=========================================="
echo ""
echo "1. Vá para AWS Console → RDS → Query Editor"
echo "2. Conecte ao database: $DB_NAME"
echo "3. Cole o conteúdo de: /tmp/create-all-tables.sql"
echo "4. Execute"
echo ""
echo "=========================================="
echo "Opção 3: Permitir conexão temporária"
echo "=========================================="
echo ""
echo "⚠️  NÃO RECOMENDADO PARA PRODUÇÃO!"
echo ""
echo "# Permitir seu IP no Security Group do RDS:"
echo "aws ec2 authorize-security-group-ingress \\"
echo "  --group-id sg-0622d28c048e22fa8 \\"
echo "  --protocol tcp \\"
echo "  --port 5432 \\"
echo "  --cidr \$(curl -s ifconfig.me)/32 \\"
echo "  --region us-east-1 \\"
echo "  --profile personal"
echo ""
echo "# Tornar RDS publicamente acessível (temporário):"
echo "aws rds modify-db-instance \\"
echo "  --db-instance-identifier ipredencao-manager-prod-db \\"
echo "  --publicly-accessible \\"
echo "  --region us-east-1 \\"
echo "  --profile personal \\"
echo "  --apply-immediately"
echo ""
echo "# Aguarde ~2 minutos, depois conecte:"
echo "PGPASSWORD='$DB_PASSWORD' psql \\"
echo "  -h $RDS_ENDPOINT \\"
echo "  -U $DB_USER \\"
echo "  -d $DB_NAME \\"
echo "  -f /tmp/create-all-tables.sql"
echo ""
echo "# IMPORTANTE: Reverter depois:"
echo "aws rds modify-db-instance \\"
echo "  --db-instance-identifier ipredencao-manager-prod-db \\"
echo "  --no-publicly-accessible \\"
echo "  --region us-east-1 \\"
echo "  --profile personal \\"
echo "  --apply-immediately"
echo ""
echo "=========================================="
echo ""
echo "📄 SQL gerado em: /tmp/create-all-tables.sql"
echo ""

